# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_0flash_v2_mmi \
		-I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/focaltech_0flash_v2_mmi/include

obj-$(CONFIG_INPUT_TOUCHSCREEN_FOCALTECH_0FLASH_MMI) := focaltech_0flash_v2_mmi.o
focaltech_0flash_v2_mmi-objs += focaltech_core.o
focaltech_0flash_v2_mmi-objs += focaltech_esdcheck.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_fun.o
focaltech_0flash_v2_mmi-objs += focaltech_ex_mode.o
focaltech_0flash_v2_mmi-objs += focaltech_flash.o
focaltech_0flash_v2_mmi-objs += focaltech_gesture.o
focaltech_0flash_v2_mmi-objs += focaltech_point_report_check.o
focaltech_0flash_v2_mmi-objs += focaltech_spi.o

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_ENABLE_DOUBLE_TAP)),)
	ccflags-y += -DFOCALTECH_SENSOR_EN
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_NOTIFY_TOUCH_STATE)),)
        ccflags-y += -DFTS_SET_TOUCH_STATE
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_ESD_EN)),)
ccflags-y += -DFOCALTECH_ESD_EN
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_PANEL_NOTIFICATIONS)),)
ccflags-y += -DFOCALTECH_CONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_DEBUG_EN)),)
ccflags-y += -DFOCALTECH_DEBUG_EN
endif

ccflags-y += -DCONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME_FT8057

ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_PINCTRL_EN)),)
ccflags-y += -DFOCALTECH_PINCTRL_EN
endif

ifneq ($(filter m y,$(CONFIG_FOCALTECH_LAST_TIME)),)
	ccflags-y += -DFTS_LAST_TIME_EN
endif
